server:
  interface: 0.0.0.0
  port: 5353
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  access-control: 0.0.0.0/0 refuse
  access-control: 10.78.53.0/24 allow
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  harden-below-nxdomain: yes
  qname-minimisation: yes
  prefetch: yes
  cache-min-ttl: 0
  cache-max-ttl: 86400
  so-sndbuf: 0
  verbosity: 1
