server:
  interface: 0.0.0.0
  port: 5353
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  access-control: 10.77.53.0/24 allow
  hide-identity: yes
  hide-version: yes
  qname-minimisation: yes
  prefetch: no
  cache-min-ttl: 0
  cache-max-ttl: 86400
  so-sndbuf: 0
  verbosity: 1
  local-zone: "test." nodefault

forward-zone:
  name: "."
  forward-addr: 10.77.53.10@5353
